# Copyright 2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, without warranties or
# conditions of any kind, EITHER EXPRESS OR IMPLIED. See the License for the
# specific language governing permissions and limitations under the License.

require "rspec/core/rake_task"

desc "Run unit tests"
RSpec::Core::RakeTask.new(:spec)

desc 'Generates code from Thirft files'
namespace "install" do
  task :thrift do |t|
    `rm -rf thrift`
    `mkdir -p thrift`
    Dir["#{File.dirname(__FILE__)}/../../thrift//*.thrift"].each do |file|
      puts `thrift --gen rb --recurse -out #{File.dirname(__FILE__)}/thrift #{file}`
    end
  end
end

task :default => :spec
