#!/bin/bash
set -x -e

# Use branch name as version of RPM. We cannot have '-' in the RPM version so that
# we cannot have SNAPSHOT at the end as we have with tar file.
# Resulting RPM will be named as 'photon-controller-core-develop.rpm' for develop branch
# and 'photon-controller-core-v0.9.1.rpm' for v0.9.1 branch.
VERSION=${GERRIT_BRANCH:-`git rev-parse --abbrev-ref HEAD`}

ROOT=`git rev-parse --show-toplevel`
SOURCES_DIR="${ROOT}/java/rpms/SOURCES"
TEMP_DIR=$(mktemp -d "${ROOT}/create_tar.XXXXX")
TAR_PATH="/java/photon-controller-core/build/distributions/"
TAR_PREFIX="photon-controller-core"
RPM_PREFIX="photon-controller"
trap "rm -rf ${TEMP_DIR}; rm -rf ${SOURCES_DIR};" EXIT

# Create source tar file for use by RPM spec file
mkdir -p "${SOURCES_DIR}"

cd "${TEMP_DIR}"
FILENAME=`find "${ROOT}${TAR_PATH}" -iname "${TAR_PREFIX}*.tar"`
tar -xf "${FILENAME}"
RPM_DIR="${RPM_PREFIX}-${VERSION}"
mv ${TAR_PREFIX}* "${RPM_DIR}"
tar -czf "${SOURCES_DIR}/${RPM_DIR}.tar" "${RPM_DIR}"

cp "${SOURCES_DIR}"/../SPECS/* "${SOURCES_DIR}"

DEBUG_OPTIONS=""
if [ "$DEBUG" == "true" ]; then
  DEBUG_OPTIONS="-t"
fi

# Build the RPM package inside Photon OS (container) so that right dependencies
# are generated by the package builder for PhotonOS linux distribution.
docker pull vmware/photon-controller-rpm-builder
docker run -i ${DEBUG_OPTIONS} \
  -v "${ROOT}":/photon-controller \
  -v "${ROOT}"/java/rpms/SOURCES/:/usr/src/photon/SOURCES \
  -v "${ROOT}"/java/build/RPMS:/usr/src/photon/RPMS \
  -w /photon-controller/java/rpms \
  vmware/photon-controller-rpm-builder \
  scripts/create-rpm-helper.sh "${VERSION}" "${DEBUG}"

# Verify rpm was created and could be installed.
docker run -i \
  -v "${ROOT}"/java/build/RPMS/x86_64:/rpms \
  vmware/photon-controller-rpm-builder \
  bash -c 'ls /rpms/photon-controller*.rpm | xargs rpm -Uvh && [ -d /opt/vmware/photon-controller ]'
