#!/bin/bash +xe

MULTI_HOST=$1
LIGHTWAVE_PASSWORD=$2
LW_CONTAINER_VERSION=$3
PC_CONTAINER_VERSION=$4

LIGHTWAVE_PARTNER_0=${LIGHTWAVE_PARTNER_0:-192.168.114.2}
LIGHTWAVE_PARTNER_1=${LIGHTWAVE_PARTNER_1:-192.168.114.3}
LIGHTWAVE_PARTNER_2=${LIGHTWAVE_PARTNER_2:-192.168.114.4}

if [ "$DEBUG" == "1" ]; then
  set -xe
fi

./helpers/run-lw-container.sh $LIGHTWAVE_PARTNER_0 $LIGHTWAVE_PARTNER_0 $LIGHTWAVE_PASSWORD standalone 1 $LW_CONTAINER_VERSION $PC_CONTAINER_VERSION

if [ "$MULTI_HOST" == "1" ]; then
  ./helpers/run-lw-container.sh $LIGHTWAVE_PARTNER_1 $LIGHTWAVE_PARTNER_0 $LIGHTWAVE_PASSWORD partner 2 $LW_CONTAINER_VERSION $PC_CONTAINER_VERSION
  ./helpers/run-lw-container.sh $LIGHTWAVE_PARTNER_2 $LIGHTWAVE_PARTNER_0 $LIGHTWAVE_PASSWORD partner 3 $LW_CONTAINER_VERSION $PC_CONTAINER_VERSION
fi

exit 0
