#!/bin/bash

tools=$(readlink -nf $(dirname $0))
source $tools/common.sh

function usage() {
  echo "Usage: $0 LIGHTWAVE_ADDRESS LIGHTWAVE_PASSWORD LIGHTWAVE_DOMAIN KEYSTORE_FILE KEYSTORE_PASSWORD" 1>&2
  echo
  echo "Supplied args:"
  echo $*
  exit 1
}

lightwave_address=""
lightwave_password=""
lightwave_domain=""
keystore_file=""
keystore_password=""

if [ "$#" -lt 3 ]
then
  usage $*
fi

lightwave_address=$1
shift
lightwave_password=$1
shift
lightwave_domain=$1
shift
keystore_file=$1
shift
keystore_password=$1
shift

export JAVA_HOME="/usr/java/default"
export PATH=$PATH:$JAVA_HOME/bin:/opt/vmware/bin:/opt/likewise/bin

function get_ca_cert() {
  # Get CA certificates from lightwave server to add to trust store
  curl -X GET -k -sS -H "Content-Type: application/json" \
    https://$lightwave_address/idm/tenant/$lightwave_domain/certificates?scope=tenant > ca_cert.json

  # Parse the JSON response to get the CA certificates and put them in separate files
  python << END
import json,sys
with open('ca_cert.json') as data_file:
  json_data = json.load(data_file);
i = 0
for cert in json_data[0]['certificates']:
  i += 1
  cert_file = open('ca_' + str(i) + '.crt', 'w')
  cert_file.write(cert['encoded'] + "\n")
END

  # Import the CA certificates into trust store
  for cert_file in *.crt
  do
    # Generate random alias for cert
    alias=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c10)

    # Import the CA cert into trust store
    keytool -import -trustcacerts -alias $alias -file $cert_file -keystore $keystore_file \
      -storepass $keystore_password -noprompt
  done
}

function generate_certificate() {
  # Fill in the hostname and ip address for generating a machine certificate
  full_hostname="$(hostname -f)"
  ip_address="$(hostname -i)"
  sed -i s/IPAddress.*/"IPAddress = $ip_address"/ /opt/vmware/share/config/certool.cfg
  sed -i s/Hostname.*/"Hostname = $full_hostname"/ /opt/vmware/share/config/certool.cfg

  mkdir -p /etc/keys

  # Generate keys if they don't exist
  if [ ! -f /etc/keys/machine.privkey ] || [ ! -f /etc/keys/machine.pubkey ]; then
    certool --genkey --privkey=/etc/keys/machine.privkey --pubkey=/etc/keys/machine.pubkey \
      --srp-upn administrator@$lightwave_domain --srp-pwd $lightwave_password --server $lightwave_address
  fi

  # Generate certificate if it doesn't exist
  if [ ! -f /etc/keys/machine.crt ]; then
    certool --gencert --privkey=/etc/keys/machine.privkey --cert=/etc/keys/machine.crt \
      --srp-upn administrator@$lightwave_domain --srp-pwd $lightwave_password \
      --server $lightwave_address --config /opt/vmware/share/config/certool.cfg
  fi

  # Generate pkcs12 keystore
  openssl pkcs12 -export -in /etc/keys/machine.crt -inkey /etc/keys/machine.privkey -out keystore.p12 \
    -name MACHINE_CERT -password pass:$keystore_password

  # Convert it into JKS
  keytool -importkeystore -deststorepass $keystore_password -destkeypass $keystore_password \
    -destkeystore $keystore_file -srckeystore keystore.p12 -srcstoretype PKCS12 -srcstorepass $keystore_password \
    -alias MACHINE_CERT

  # Restrict permission on the key files
  chmod 0400 /etc/keys/machine.privkey
  chmod 0444 /etc/keys/machine.pubkey
}

generate_certificate
get_ca_cert
