#!/bin/sh -xe

LIGHTWAVE_PARTNER_0=${LIGHTWAVE_PARTNER_0:-192.168.114.2}
LIGHTWAVE_LOAD_BALANCER_IP=$(docker inspect --format '{{ .Node.IP }}' haproxy) || true

if [ "${LIGHTWAVE_LOAD_BALANCER_IP}TEST" ==  "TEST" ]; then
  LIGHTWAVE_LOAD_BALANCER_IP=$(docker-machine ip default)
fi

PHOTON_PEER_0=${PHOTON_PEER_0:-192.168.114.11}
PHOTON_PEER_1=${PHOTON_PEER_1:-192.168.114.12}
PHOTON_PEER_2=${PHOTON_PEER_2:-192.168.114.13}

./run-pc-container.sh $PHOTON_PEER_0 $PHOTON_PEER_1 $PHOTON_PEER_2 $LIGHTWAVE_PARTNER_0 $LIGHTWAVE_LOAD_BALANCER_IP 1
./run-pc-container.sh $PHOTON_PEER_1 $PHOTON_PEER_0 $PHOTON_PEER_2 $LIGHTWAVE_PARTNER_0 $LIGHTWAVE_LOAD_BALANCER_IP 2
./run-pc-container.sh $PHOTON_PEER_2 $PHOTON_PEER_0 $PHOTON_PEER_1 $LIGHTWAVE_PARTNER_0 $LIGHTWAVE_LOAD_BALANCER_IP 3
