#!/bin/bash -e

vendor=$(readlink -nf $(dirname $0))

go=$vendor/go

function revision() {
  pushd src > /dev/null

  repository=$1
  revision=

  while [ "$repository" != "." ] && [ -z "$revision" ]
  do
    if [ -d $repository/.hg ]
    then
      pushd $repository > /dev/null
      revision=$(hg id -i)
      popd > /dev/null
    fi

    if [ -d $repository/.bzr ]
    then
      pushd $repository > /dev/null
      revision=$(bzr revno .)
      popd > /dev/null
    fi

    if [ -d $repository/.git ]
    then
      pushd $repository > /dev/null
      if [ -n "$GO_GET_TAG" ]
      then
        git checkout $GO_GET_TAG
      fi
      revision=$(git rev-parse HEAD)
      # remove .git so git doesn't think this is a submodule
      rm -rf .git
      popd > /dev/null
    fi

    repository=$(dirname $repository)
  done

  if [ -z "$revision" ]
  then
    revision="(unknown)"
  fi

  echo $revision

  popd > /dev/null
}

function get() {
  src=$vendor/src/$1
  if [ -d "$src" ] ; then
    echo "$src already exists"
    exit 1
  else
    echo "Getting $1... "
    $go get -d $1

    printf "Added $1\n\n- revision $(revision $1)\n"
  fi
}

if [ -n "$1" ]
then
  get $1
else
  echo "Usage $0 IMPORT_PATH"
  exit 1
fi
