#!/bin/bash

function usage() {
  echo "Usage: $0 HOST_ADDRESS USERNAME PASSWORD VIB_PATH LW_DOMAIN LW_ADDRESS LW_PASSWORD" 1>&2
  echo
  echo "Supplied args:"
  echo $*
  exit 1
}

host_address=""
username=""
password=""
vib_path=""
lightwave_domain=""
lightwave_address=""
lightwave_password=""

if [ "$#" -lt 7 ]
then
  usage $*
fi

host_address=$1
shift
username=$1
shift
password=$1
shift
vib_path=$1
shift
lightwave_domain=$1
shift
lightwave_address=$1
shift
lightwave_password=$1
shift


while getopts d:l:n:h flag
do
  case $flag in
    ?)
      usage $*
      ;;
  esac
done

SSH_OPTS="-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

function install_vib() {
  sshpass -p "$password" ssh $SSH_OPTS ${username}@${host_address} esxcli software vib install -f -v $vib_path
  if [[ $? -ne 0 ]]
  then
    echo "retrying installing vib"
	  sshpass -p "$password" ssh $SSH_OPTS ${username}@${host_address} esxcli software vib install -f -v $vib_path

	  if [[ $? -ne 0 ]]
	  then
	    exit 1
	  fi
	fi
  sshpass -p "$password"  ssh $SSH_OPTS ${username}@${host_address} esxcli software vib list
}

# Add java home and other required binaries to path. We need this here even though we are doing this during container
# build because systemd service does not seem to honor the environment variables set at container build time.
export JAVA_HOME="/usr/java/default"
export PATH=$PATH:$JAVA_HOME/bin:/opt/esxcli:/opt/vmware/bin:/opt/likewise/bin

host_cert_dir="/etc/vmware/ssl"

function join_lightwave_domain() {
  # Join lightwave domain. param 1 means use notify services instead of put node to maintenance mode
  join_domain_cmd="/usr/lib/vmware/ic-deploy/bin/configure-lightwave.py ${lightwave_address} ${lightwave_domain} '${lightwave_password}' 1 ${host_address} '$password'"
  sshpass -p "$password" ssh $SSH_OPTS ${username}@${host_address} $join_domain_cmd

  # Listing /etc/vmware/ssl contents after copying
  echo "listing ${host_cert_dir} contents after copying"
  sshpass -p "$password" ssh $SSH_OPTS ${username}@${host_address} ls -l ${host_cert_dir}

  # restart photon-controller-agent
  restart_agent_cmd="if [ -f /etc/init.d/photon-controller-agent ]; then /etc/init.d/photon-controller-agent restart; fi"
  echo $restart_agent_cmd
  sshpass -p "$password" ssh -tt $SSH_OPTS ${username}@${host_address} $restart_agent_cmd
}

sshpass -p "$password"  ssh $SSH_OPTS ${username}@${host_address} date
echo "vib_path=${vib_path}"

install_vib

if [[ "$vib_path" == *"lightwave"* ]]; then
  join_lightwave_domain
fi

sshpass -p "$password"  ssh $SSH_OPTS ${username}@${host_address} date