# Copyright 2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License. You may obtain a copy of
# the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed
# under the License is distributed on an "AS IS" BASIS, without warranties or
# conditions of any kind, EITHER EXPRESS OR IMPLIED. See the License for the
# specific language governing permissions and limitations under the License.

source "http://rubygems.org"

gem 'ipaddress', '~> 0.8.0'
gem 'netaddr', '~> 1.5.0'
gem "faraday", "~>0.8.7"
gem "json", "~>1.8"
gem "rake", "~>10"
gem "rspec", "~>2.14"
gem "rspec_junit_formatter", "~>0.1.6"
gem "zookeeper", "~>1.4.9"
gem "net-ssh", "~>2.9.2"
gem "net-sftp", "~>2.1.2"
gem "net-ping", "~>1.7.6"
gem "parallel_tests", "~>1.7.0"
#gem "thrift", "~>0.9.2"
