#!/bin/bash -e

function usage() {
  echo "Usage $0 ISO_NAME USER_DATA META_DATA" 1>&2
  echo
  echo "Supplied args:"
  echo $*
  exit 1
}

# Require at least 3 initial arguments
[ $# -ge 3 ] || usage

iso_file=$1
shift

user_data_file=$1
shift

meta_data_file=$1
shift

cp $user_data_file user-data
cp $meta_data_file meta-data
