#!/bin/bash
# Copyright 2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, without
# warranties or conditions of any kind, EITHER EXPRESS OR IMPLIED.  See the
# License for then specific language governing permissions and limitations
# under the License.

#
# Create SSH key in tools/.ssh if it not yet exists.
#
# Authorize this key with the specified hosts,
# using the specified password to log in.
#

if [ $# -lt 1 ]
then
  echo "Usage: $0 [--password PASSWORD] URI ..."
  echo
  echo "Supplied args:"
  echo $*
  exit 1
fi

if [ "$(uname)" == "Darwin" ]; then
        # On OSX default BSD version of sed and readlink do not behave same as GNU versions.
        # brew install coreutils gnu-sed
        READLINK=greadlink
else
        READLINK=readlink
fi

tools=$($READLINK -nf $(dirname $0)/)
source $tools/common.sh

password=""

# Parse options
while true
do
  case "$1" in
  --password)
    password="$2"
    shift
    shift
  ;;
  -*)
    echo "Unknown option: $1"
    exit 1
  ;;
  *)
    break
  ;;
  esac
done

if [ -z "$password" ]
then
  echo "password is required"
  exit 1
fi

if [ ! -f $tools/.ssh/id_rsa ]
then
  echo "missing ssh key"
  exit 1
fi

for arg in "$@"
do
  # ssh-copy-id checks if the key is already in place or not.
  # Use system-side ssh to bypass the options bin/ssh enforces.
  env PATH=/usr/bin:$PATH \
    sshpass \
      -p "$password" \
    $tools/ssh-copy-id \
      -i $tools/.ssh/id_rsa.pub \
      -o UserKnownHostsFile=/dev/null \
      -o StrictHostKeyChecking=no \
      "$arg"
done
