#!/bin/bash
# Copyright 2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, without
# warranties or conditions of any kind, EITHER EXPRESS OR IMPLIED.  See the
# License for then specific language governing permissions and limitations
# under the License.

#
# Run ssh/scp with the correct key, without host key checking.
#

if [ "$(uname)" == "Darwin" ]; then
        # On OSX default BSD version of sed and readlink do not behave same as GNU versions.
        # brew install coreutils gnu-sed
        READLINK=greadlink
else
        READLINK=readlink
fi

basename=$(basename "$0")
root=$($READLINK -nf $(dirname "$0")/)

# Format arguments to preserve special characters
quoted_args=""
for arg in "$@"
do
  quoted_args="$quoted_args $(printf "%q" "$arg")"
done

identity_file=$root/.ssh/id_rsa
if [ -f $identity_file ]
then
  identity="-i $identity_file"
fi

/usr/bin/$basename $identity \
  -o UserKnownHostsFile=/dev/null \
  -o StrictHostKeyChecking=no \
  -o LogLevel=quiet \
  $quoted_args
