#!/bin/bash -xe
inputVM=$1
outputVM=$2
customscript=$3

ovftool --lax -o ${inputVM}.ova ${outputVM}.ovf
oldOvfSha=$(sha1sum ${outputVM}.ovf | awk '{ print $1 }')

# Overwrite VirtualBox related stuff with vmware related values
# Overwrite VirtualBox related stuff with vmware related values
sed -i.bak 's/virtualbox-2.2/vmx-04 vmx-06 vmx-07 vmx-09/' ${outputVM}.ovf
sed -i.bak 's/<rasd:Caption>sataController0/<rasd:Caption>SCSIController/' ${outputVM}.ovf
sed -i.bak 's/<rasd:Description>SATA Controller/<rasd:Description>SCSI Controller/' ${outputVM}.ovf
sed -i.bak 's/<rasd:ElementName>sataController0/<rasd:ElementName>SCSIController/' ${outputVM}.ovf
sed -i.bak 's/<rasd:ResourceSubType>AHCI/<rasd:ResourceSubType>lsilogic/' ${outputVM}.ovf
sed -i.bak 's/<rasd:ResourceType>20</<rasd:ResourceType>6</' ${outputVM}.ovf
sed -i.bak $'s@<VirtualHardwareSection@ <EulaSection> \
      <Info>End User License Agreement</Info> \
      <License msgid="eula">Use of Lightwave by VMware and Photon Controller by VMware are subject to the VMware End User License Agreement found below.  Use of Photon OS is subject to the VMware End User License Agreement for Photon OS that follows after the VMware End User License Agreement. \
 \
VMWARE END USER LICENSE AGREEMENT \
 \
PLEASE NOTE THAT THE TERMS OF THIS END USER LICENSE AGREEMENT SHALL GOVERN YOUR USE OF THE SOFTWARE, REGARDLESS OF ANY TERMS THAT MAY APPEAR DURING THE INSTALLATION OF THE SOFTWARE. \
 \
IMPORTANT-READ CAREFULLY:   BY DOWNLOADING, INSTALLING, OR USING THE SOFTWARE, YOU (THE INDIVIDUAL OR LEGAL ENTITY) AGREE TO BE BOUND BY THE TERMS OF THIS END USER LICENSE AGREEMENT (\&quot;EULA\&quot;).  IF YOU DO NOT AGREE TO THE TERMS OF THIS EULA, YOU MUST NOT DOWNLOAD, INSTALL, OR USE THE SOFTWARE, AND YOU MUST DELETE OR RETURN THE UNUSED SOFTWARE TO THE VENDOR FROM WHICH YOU ACQUIRED IT WITHIN THIRTY (30) DAYS AND REQUEST A REFUND OF THE LICENSE FEE, IF ANY, THAT YOU PAID FOR THE SOFTWARE. \
 \
EVALUATION LICENSE.  If You are licensing the Software for evaluation purposes, Your use of the Software is only permitted in a non-production environment and for the period limited by the License Key.  Notwithstanding any other provision in this EULA, an Evaluation License of the Software is provided \&quot;AS-IS\&quot; without indemnification, support or warranty of any kind, expressed or implied. \
 \
1.	DEFINITIONS. \
 \
1.1	\&quot;Affiliate\&quot; means, with respect to a party at a given time, an entity that then is directly or indirectly controlled by, is under common control with, or controls that party, and here \&quot;control\&quot; means an ownership, voting or similar interest representing fifty percent (50%) or more of the total interests then outstanding of that entity. \
 \
1.2	\&quot;Documentation\&quot; means that documentation that is generally provided to You by VMware with the Software, as revised by VMware from time to time, and which may include end user manuals, operation instructions, installation guides, release notes, and on-line help files regarding the use of the Software. \
 \
1.3	\&quot;Guest Operating Systems\&quot; means instances of third-party operating systems licensed by You, installed in a Virtual Machine and run using the Software. \
 \
1.4	\&quot;Intellectual Property Rights\&quot; means all worldwide intellectual property rights, including without limitation, copyrights, trademarks, service marks, trade secrets, know how, inventions, patents, patent applications, moral rights and all other proprietary rights, whether registered or unregistered. \
 \
1.5	\&quot;License\&quot; means a license granted under Section 2.1 (General License Grant). \
 \
1.6    	\&quot;License Key\&quot; means a serial number that enables You to activate and use the Software. \
 \
1.7	\&quot;License Term\&quot; means the duration of a License as specified in the Order. \
 \
1.8	\&quot;License Type\&quot; means the type of License applicable to the Software, as more fully described in the Order. \
 \
1.9	\&quot;Open Source Software\&quot; or \&quot;OSS\&quot; means software components embedded in the Software and provided under separate license terms, which can be found either in the open_source_licenses.txt file (or similar file) provided within the Software or at www.vmware.com/download/open_source.html. \
 \
1.10	\&quot;Order\&quot; means a purchase order, enterprise license agreement, or other ordering document issued by You to VMware or a VMware authorized reseller that references and incorporates this EULA and is accepted by VMware as set forth in Section 4 (Order). \
1.11	\&quot;Product Guide\&quot; means the current version of the VMware Product Guide at the time of Your Order, copies of which are found at www.vmware.com/download/eula. \
 \
1.12	\&quot;Support Services Terms\&quot; means VMware\&apos;s then-current support policies, copies of which are posted at www.vmware.com/support/policies. \
 \
1.13	\&quot;Software\&quot; means the VMware Tools and the VMware computer programs listed on VMware\&apos;s commercial price list to which You acquire a license under an Order, together with any software code relating to the foregoing that is provided to You pursuant to a support and subscription service contract and that is not subject to a separate license agreement. \
 \
1.14	\&quot;Territory\&quot; means the country or countries in which You have been invoiced; provided, however, that if You have been invoiced within any of the European Economic Area member states, You may deploy the corresponding Software throughout the European Economic Area. \
 \
1.15	\&quot;Third Party Agent\&quot; means a third party delivering information technology services to You pursuant to a written contract with You. \
 \
1.16	\&quot;Virtual Machine\&quot; means a software container that can run its own operating system and execute applications like a physical machine. \
 \
1.17	\&quot;VMware\&quot; means VMware, Inc., a Delaware corporation, if You are purchasing Licenses or services for use in the United States and VMware International Limited, a company organized and existing under the laws of Ireland, for all other purchases. \
1.18	\&quot;VMware Tools\&quot; means the suite of utilities and drivers, Licensed by VMware under the \&quot;VMware Tools\&quot; name, that can be installed in a Guest Operating System to enhance the performance and functionality of a Guest Operating System when running in a Virtual Machine. \
 \
2.		LICENSE GRANT. \
 \
2.1	General License Grant.  VMware grants to You a non-exclusive, non-transferable (except as set forth in Section 12.1 (Transfers; Assignment)) license to use the Software and the Documentation during the period of the license and within the Territory, solely for Your internal business operations, and subject to the provisions of the Product Guide. Unless otherwise indicated in the Order, licenses granted to You will be perpetual, will be for use of object code only, and will commence on either delivery of the physical media or the date You are notified of availability for electronic download. \
 \
2.2	Third Party Agents. Under the License granted to You in Section 2.1 (General License Grant) above, You may permit Your Third Party Agents to access, use and/or operate the Software on Your behalf for the sole purpose of delivering services to You, provided that You will be fully responsible for Your Third Party Agents\&apos; compliance with terms and conditions of this EULA and any breach of this EULA by a Third Party Agent shall be deemed to be a breach by You. \
 \
2.3       Copying Permitted.  You may copy the Software and Documentation as necessary to install and run the quantity of copies licensed, but otherwise for archival purposes only. \
 \
2.4	Benchmarking.  You may use the Software to conduct internal performance testing and benchmarking studies. You may only publish or otherwise distribute the results of such studies to third parties as follows:  (a) if with respect to VMware\&apos;s Workstation or Fusion products, only if You provide a copy of Your study to benchmark\@vmware.com prior to distribution;   (b) if with respect to any other Software, only if VMware has reviewed and approved of the methodology, assumptions and other parameters of the study  (please contact VMware at benchmark\@vmware.com to request such review and approval) prior to such publication and distribution. \
 \
2.5	VMware Tools.  You may distribute the VMware Tools to third parties solely when installed in a Guest Operating System within a Virtual Machine. You are liable for compliance by those third parties with the terms and conditions of this EULA. \
 \
2.6	Open Source Software.  Notwithstanding anything herein to the contrary, Open Source Software is licensed to You under such OSS\&apos;s own applicable license terms, which can be found in the open_source_licenses.txt file, the Documentation or as applicable, the corresponding source files for the Software available at www.vmware.com/download/open_source.html. These OSS license terms are consistent with the license granted in Section 2 (License Grant), and may contain additional rights benefiting You.  The OSS license terms shall take precedence over this EULA to the extent that this EULA imposes greater restrictions on You than the applicable OSS license terms. To the extent the license for any Open Source Software requires VMware to make available to You the corresponding source code and/or modifications (the \&quot;Source Files\&quot;), You may obtain a copy of the applicable Source Files from VMware\&apos;s website at www.vmware.com/download/open_source.html or by sending a written request, with Your name and address to: VMware, Inc., 3401 Hillview Avenue, Palo Alto, CA 94304, United States of America. All requests should clearly specify:  Open Source Files Request, Attention: General Counsel.  This offer to obtain a copy of the Source Files is valid for three years from the date You acquired this Software. \
 \
3.	RESTRICTIONS; OWNERSHIP. \
 \
3.1	License Restrictions.  Without VMware\&apos;s prior written consent, You must not, and must not allow any third party to: (a) use Software in an application services provider, service bureau, or similar capacity for third parties, except that You may use the Software to deliver hosted services to Your Affiliates; (b) disclose to any third party the results of any benchmarking testing or comparative or competitive analyses of VMware\&apos;s Software done by or on behalf of You, except as specified in Section 2.4 (Benchmarking); (c) make available Software in any form to anyone other than Your employees or contractors reasonably acceptable to VMware and require access to use Software on behalf of You in a matter permitted by this EULA, except as specified in Section 2.2 (Third Party Agents); (d) transfer or sublicense Software or Documentation to an Affiliate or any third party, except as expressly permitted in Section 12.1 (Transfers; Assignment); (e) use Software in conflict with the terms and restrictions of the Software\&apos;s licensing model and other requirements specified in Product Guide and/or VMware quote; (f) except to the extent permitted by applicable mandatory law, modify, translate, enhance, or create derivative works from the Software, or  reverse engineer, decompile, or otherwise attempt to derive source code from the Software, except as specified in Section 3.2 (Decompilation); (g) remove any copyright or other proprietary notices on or in any copies of Software; or (h) violate or circumvent any technological restrictions within the Software or specified in this EULA, such as via software or services. \
 \
3.2	Decompilation.  Notwithstanding the foregoing, decompiling the Software is permitted to the extent the laws of the Territory give You the express right to do so to obtain information necessary to render the Software interoperable with other software; provided, however, You must first request such information from VMware, provide all reasonably requested information to allow VMware to assess Your claim, and VMware may, in its discretion, either provide such interoperability information to You, impose reasonable conditions, including a reasonable fee, on such use of the Software, or offer to provide alternatives to ensure that VMware\&apos;s proprietary rights in the Software are protected and to reduce any adverse impact on VMware\&apos;s proprietary rights. \
 \
3.3	Ownership.  The Software and Documentation, all copies and portions thereof, and all improvements, enhancements, modifications and derivative works thereof, and all Intellectual Property Rights therein, are and shall remain the sole and exclusive property of VMware and its licensors. Your rights to use the Software and Documentation shall be limited to those expressly granted in this EULA and any applicable Order.  No other rights with respect to the Software or any related Intellectual Property Rights are implied.  You are not authorized to use (and shall not permit any third party to use) the Software, Documentation or any portion thereof except as expressly authorized by this EULA or the applicable Order.  VMware reserves all rights not expressly granted to You. VMware does not transfer any ownership rights in any Software. \
 \
3.4	Guest Operating Systems.  Certain Software allows Guest Operating Systems and application programs to run on a computer system. You acknowledge that You are responsible for obtaining and complying with any licenses necessary to operate any such third-party software. \
 \
4.	ORDER. Your Order is subject to this EULA.  No Orders are binding on VMware until accepted by VMware.  Orders for Software are deemed to be accepted upon VMware\&apos;s delivery of the Software included in such Order. Orders issued to VMware do not have to be signed to be valid and enforceable. \
 \
5.	RECORDS AND AUDIT.  During the License Term for Software and for two (2) years after its expiration or termination, You will maintain accurate records of Your use of the Software sufficient to show compliance with the terms of this EULA. During this period, VMware will have the right to audit Your use of the Software to confirm compliance with the terms of this EULA. That audit is subject to reasonable notice by VMware and will not unreasonably interfere with Your business activities. VMware may conduct no more than one (1) audit in any twelve (12) month period, and only during normal business hours. You will reasonably cooperate with VMware and any third party auditor and will, without prejudice to other rights of VMware, address any non-compliance identified by the audit by promptly paying additional fees. You will promptly reimburse VMware for all reasonable costs of the audit if the audit reveals either underpayment of more than five (5%) percent of the Software fees payable by You for the period audited, or that You have materially failed to maintain accurate records of Software use. \
 \
6.	SUPPORT AND SUBSCRIPTION SERVICES.  Except as expressly specified in the Product Guide, VMware does not provide any support or subscription services for the Software under this EULA.  You have no rights to any updates, upgrades or extensions or enhancements to the Software developed by VMware unless you separately purchase VMware support or subscription services.  These support or subscription services are subject to the Support Services Terms. \
 \
7.	   WARRANTIES. \
 \
7.1	Software Warranty, Duration and Remedy. VMware warrants to You that the Software will, for a period of ninety (90) days following notice of availability for electronic download or delivery (\&quot;Warranty Period\&quot;), substantially conform to the applicable Documentation, provided that the Software: (a) has been properly installed and used at all times in accordance with the applicable Documentation; and (b) has not been modified or added to by persons other than VMware or its authorized representative. VMware will, at its own expense and as its sole obligation and Your exclusive remedy for any breach of this warranty, either replace that Software or correct any reproducible error in that Software reported to VMware by You in writing during the Warranty Period. If VMware determines that it is unable to correct the error or replace the Software, VMware will refund to You the amount paid by You for that Software, in which case the License for that Software will terminate. \
 \
7.2	Software Disclaimer of Warranty.  OTHER THAN THE WARRANTY ABOVE, AND TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, VMWARE AND ITS SUPPLIERS MAKE NO OTHER EXPRESS WARRANTIES UNDER THIS EULA, AND DISCLAIM ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT, AND ANY WARRANTY ARISING BY STATUTE, OPERATION OF LAW, COURSE OF DEALING OR PERFORMANCE, OR USAGE OF TRADE. VMWARE AND ITS LICENSORS DO NOT WARRANT THAT THE SOFTWARE WILL OPERATE UNINTERRUPTED OR THAT IT WILL BE FREE FROM DEFECTS OR THAT IT WILL MEET YOUR REQUIREMENTS. \
 \
8.	    INTELLECTUAL PROPERTY INDEMNIFICATION. \
 \
8.1	Defense and Indemnification.  Subject to the remainder of this Section 8 (Intellectual Property Indemnification), VMware shall defend You against any third party claim that the Software infringes any patent, trademark or copyright of such third party, or misappropriates a trade secret (but only to the extent that the misappropriation is not a result of Your actions) under the laws of: (a) the United States and Canada; (b) the European Economic Area; (c) Australia; (d) New Zealand; (e) Japan; or (f) the People\&apos;s Republic of China, to the extent that such countries are part of the Territory for the License (\&quot;Infringement Claim\&quot;) and indemnify You from the resulting costs and damages finally awarded against You to such third party by a court of competent jurisdiction or agreed to in settlement. The foregoing obligations are applicable only if You:  (i) promptly notify VMware in writing of the Infringement Claim; (ii) allow VMware sole control over the defense for the claim and any settlement negotiations; and (iii) reasonably cooperate in response to VMware requests for assistance.  You may not settle or compromise any Infringement Claim without the prior written consent of VMware. \
8.2	Remedies.  If the alleged infringing Software become, or in VMware\&apos;s opinion be likely to become, the subject of an Infringement Claim, VMware will, at VMware\&apos;s option and expense, do one of the following:  (a) procure the rights necessary for You to make continued use of the affected Software; (b) replace or modify the affected Software to make it non-infringing; or (c) terminate the License to the affected Software and discontinue the related support services, and, upon Your certified deletion of the affected Software, refund: (i) the fees paid by You for the License to the affected Software, less straight-line depreciation over a three (3) year useful life beginning on the date such Software was delivered; and (ii) any pre-paid service fee attributable to related support services to be delivered after the date such service is stopped. Nothing in this Section 8.2 (Remedies) shall limit VMware\&apos;s obligation under Section 8.1 (Defense and Indemnification) to defend and indemnify You, provided that You replace the allegedly infringing Software upon VMware\&apos;s making alternate Software available to You and/or You discontinue using the allegedly infringing Software upon receiving VMware\&apos;s notice terminating the affected License. \
8.3	Exclusions.  Notwithstanding the foregoing, VMware will have no obligation under this Section 8 (Intellectual Property Indemnification) or otherwise with respect to any claim based on:  (a) a combination of Software with non-VMware products (other than non-VMware products that are listed on the Order and used in an unmodified form); (b) use for a purpose or in a manner for which the Software was not designed; (c) use of any older version of the Software when use of a newer VMware version would have avoided the infringement; (d) any modification to the Software made without VMware\&apos;s express written approval; (e) any claim that relates to open source software or freeware technology or any derivatives or other adaptations thereof that is not embedded by VMware into Software listed on VMware\&apos;s commercial price list; or (f) any Software provided on a no charge, beta or evaluation basis.  THIS SECTION 8 (INTELLECTUAL PROPERTY INDEMNIFICATION) STATES YOUR SOLE AND EXCLUSIVE REMEDY AND VMWARE\&apos;S ENTIRE LIABILITY FOR ANY INFRINGEMENT CLAIMS OR ACTIONS. \
 \
9.	LIMITATION OF LIABILITY. \
 \
9.1	Limitation of Liability. TO THE MAXIMUM EXTENT MANDATED BY LAW, IN NO EVENT WILL VMWARE AND ITS LICENSORS BE LIABLE FOR ANY LOST PROFITS OR BUSINESS OPPORTUNITIES, LOSS OF USE, LOSS OF REVENUE, LOSS OF GOODWILL, BUSINESS INTERRUPTION, LOSS OF DATA, OR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES UNDER ANY THEORY OF LIABILITY, WHETHER BASED IN CONTRACT, TORT, NEGLIGENCE, PRODUCT LIABILITY, OR OTHERWISE.  BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE PRECEDING LIMITATION MAY NOT APPLY TO YOU.  VMWARE\&apos;S AND ITS LICENSORS\&apos; LIABILITY UNDER THIS EULA WILL NOT, IN ANY EVENT, REGARDLESS OF WHETHER THE CLAIM IS BASED IN CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE, EXCEED THE GREATER OF THE LICENSE FEES YOU PAID FOR THE SOFTWARE GIVING RISE TO THE CLAIM OR $5000. THE FOREGOING LIMITATIONS SHALL APPLY REGARDLESS OF WHETHER VMWARE OR ITS LICENSORS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND REGARDLESS OF WHETHER ANY REMEDY FAILS OF ITS ESSENTIAL PURPOSE. \
 \
9.2	Further Limitations.  VMware\&apos;s licensors shall have no liability of any kind under this EULA and VMware\&apos;s liability with respect to any third party software embedded in the Software shall be subject to Section 9.1 (Limitation of Liability).  You may not bring a claim under this EULA more than eighteen (18) months after the cause of action arises. \
 \
10.	    TERMINATION. \
10.1	EULA Term. The term of this EULA begins on the notice of availability for electronic download or delivery of the Software and continues until this EULA is terminated in accordance with this Section 10. \
10.2	Termination for Breach. VMware may terminate this EULA effective immediately upon written notice to You if: (a) You fail to pay any portion of the fees under an applicable Order within ten (10) days after receiving written notice from VMware that payment is past due; or (b) You breach any other provision of this EULA and fail to cure within thirty (30) days after receipt of VMware\&apos;s written notice thereof. \
10.3	Termination for Insolvency.  VMware may terminate this EULA effective immediately upon written notice to You if You: (a) terminate or suspend your business; (b) become insolvent, admit in writing Your inability to pay Your debts as they mature, make an assignment for the benefit of creditors; or become subject to control of a trustee, receiver or similar authority; or (c) become subject to any bankruptcy or insolvency proceeding. \
10.4	Effect of Termination. Upon VMware\&apos;s termination of this EULA: (a) all Licensed rights to all Software granted to You under this EULA will immediately cease; and (b) You must cease all use of all Software, and return or certify destruction of all Software and License Keys (including copies) to VMware, and return, or if requested by VMware, destroy, any related VMware Confidential Information in Your possession or control and certify in writing to VMware that You have fully complied with these requirements. Any provision will survive any termination or expiration if by its nature and context it is intended to survive, including Sections 1 (Definitions), 2.6 (Open Source Software), 3 (Restrictions; Ownership), 5 (Records and Audit), 7.2 (Software Disclaimer of Warranty), 9 (Limitation of Liability), 10 (Termination), 11 (Confidential Information) and 12 (General). \
 \
11.	CONFIDENTIAL INFORMATION. \
 \
11.1	Definition.  \&quot;Confidential Information\&quot; means information or materials provided by one party (\&quot;Discloser\&quot;) to the other party (\&quot;Recipient\&quot;) which are in tangible form and labelled \&quot;confidential\&quot; or the like, or, information which a reasonable person knew or should have known to be confidential.  The following information shall be considered Confidential Information whether or not marked or identified as such:  (a) License Keys; (b) information regarding VMware\&apos;s pricing, product roadmaps or strategic marketing plans; and (c) non-public materials relating to the Software. \
 \
11.2	Protection.  Recipient may use Confidential Information of Discloser; (a) to exercise its rights and perform its obligations under this EULA; or (b) in connection with the parties\&apos; ongoing business relationship.  Recipient will not use any Confidential Information of Discloser for any purpose not expressly permitted by this EULA, and will disclose the Confidential Information of Discloser only to the employees or contractors of Recipient who have a need to know such Confidential Information for purposes of this EULA and who are under a duty of confidentiality no less restrictive than Recipient\&apos;s duty hereunder.  Recipient will protect Confidential Information from unauthorized use, access, or disclosure in the same manner as Recipient protects its own confidential or proprietary information of a similar nature but with no less than reasonable care. \
11.3	Exceptions.  Recipient\&apos;s obligations under Section 11.2 (Protection) with respect to any Confidential Information will terminate if Recipient can show by written records that such information:  (a) was already known to Recipient at the time of disclosure by Discloser; (b) was disclosed to Recipient by a third party who had the right to make such disclosure without any confidentiality restrictions; (c) is, or through no fault of Recipient has become, generally available to the public; or (d) was independently developed by Recipient without access to, or use of, Discloser\&apos;s Information.  In addition, Recipient will be allowed to disclose Confidential Information to the extent that such disclosure is required by law or by the order of a court of similar judicial or administrative body, provided that Recipient notifies Discloser of such required disclosure promptly and in writing and cooperates with Discloser, at Discloser\&apos;s request and expense, in any lawful action to contest or limit the scope of such required disclosure. \
11.4	Data Privacy. You agree that VMware may process technical and related information about Your use of the Software which may include internet protocol address, hardware identification, operating system, application software, peripheral hardware, and non-personally identifiable Software usage statistics to facilitate the provisioning of updates, support, invoicing or online services and may transfer such information to other companies in the VMware worldwide group of companies from time to time. To the extent that this information constitutes personal data, VMware shall be the controller of such personal data. To the extent that it acts as a controller, each party shall comply at all times with its obligations under applicable data protection legislation. \
 \
12.	GENERAL. \
 \
12.1	Transfers; Assignment.  Except to the extent transfer may not legally be restricted or as permitted by VMware\&apos;s transfer and assignment policies, in all cases following the process set forth at www.vmware.com/support/policies/licensingpolicies.html, You will not assign this EULA, any Order, or any right or obligation herein or delegate any performance without VMware\&apos;s prior written consent, which consent will not be unreasonably withheld. Any other attempted assignment or transfer by You will be void. VMware may use its Affiliates or other sufficiently qualified subcontractors to provide services to You, provided that VMware remains responsible to You for the performance of the services. \
 \
12.2	Notices.  Any notice delivered by VMware to You under this EULA will be delivered via mail, email or fax. \
 \
12.3	Waiver.  Failure to enforce a provision of this EULA will not constitute a waiver. \
12.4     Severability.  If any part of this EULA is held unenforceable, the validity of all remaining parts will not be affected. \
12.5	Compliance with Laws; Export Control; Government Regulations. Each party shall comply with all laws applicable to the actions contemplated by this EULA. You acknowledge that the Software is of United States origin, is provided subject to the U.S. Export Administration Regulations, may be subject to the export control laws of the applicable territory, and that diversion contrary to applicable export control laws is prohibited. You represent that (1) you are not, and are not acting on behalf of, (a) any person who is a citizen, national, or resident of, or who is controlled by the government of any country to which the United States has prohibited export transactions; or (b) any person or entity listed on the U.S. Treasury Department list of Specially Designated Nationals and Blocked Persons, or the U.S. Commerce Department Denied Persons List or Entity List; and (2) you will not permit the Software to be used for, any purposes prohibited by law, including, any prohibited development, design, manufacture or production of missiles or nuclear, chemical or biological weapons. The Software and accompanying documentation are deemed to be \&quot;commercial computer software\&quot; and \&quot;commercial computer software documentation\&quot;, respectively, pursuant to DFARS Section 227.7202 and FAR Section 12.212(b), as applicable.  Any use, modification, reproduction, release, performing, displaying or disclosing of the Software and documentation by or for the U.S. Government shall be governed solely by the terms and conditions of this EULA. \
12.6	Construction. The headings of sections of this EULA are for convenience and are not to be used in interpreting this EULA. As used in this EULA, the word \&quot;including\&quot; means \&quot;including but not limited to\&quot;. \
12.7	Governing Law.  This EULA is governed by the laws of the State of California, United States of America (excluding its conflict of law rules), and the federal laws of the United States. To the extent permitted by law, the state and federal courts located in Santa Clara County, California will be the exclusive jurisdiction for disputes arising out of or in connection with this EULA. The U.N. Convention on Contracts for the International Sale of Goods does not apply. \
12.8	Third Party Rights.  Other than as expressly set out in this EULA, this EULA does not create any rights for any person who is not a party to it, and no person who is not a party to this EULA may enforce any of its terms or rely on any exclusion or limitation contained in it. \
12.9	Order of Precedence.  In the event of conflict or inconsistency among the Product Guide, this EULA and the Order, the following order of precedence shall apply: (a) the Product Guide, (b) this EULA and (c) the Order. With respect to any inconsistency between this EULA and an Order, the terms of this EULA shall supersede and control over any conflicting or additional terms and conditions of any Order, acknowledgement or confirmation or other document issued by You. \
12.10  Entire Agreement.  This EULA, including accepted Orders and any amendments hereto, and the Product Guide contain the entire agreement of the parties with respect to the subject matter of this EULA and supersede all previous or contemporaneous communications, representations, proposals, commitments, understandings and agreements, whether written or oral, between the parties regarding the subject matter hereof.  This EULA may be amended only in writing signed by authorized representatives of both parties. \
12.11  Contact Information.  Please direct legal notices or other correspondence to VMware, Inc., 3401 Hillview Avenue, Palo Alto, California 94304, United States of America, Attention: Legal Department. \
 \
 \
 \
 \
VMWARE END USER LICENSE AGREEMENT FOR PHOTON OS \
 \
IMPORTANT-READ CAREFULLY:   BY DOWNLOADING, INSTALLING, OR USING THE PROGRAM, YOU (THE INDIVIDUAL OR LEGAL ENTITY) AGREE TO BE BOUND BY THE TERMS OF THIS END USER LICENSE AGREEMENT (\&quot;EULA\&quot;).  IF YOU DO NOT AGREE TO THE TERMS OF THIS EULA, YOU MUST NOT DOWNLOAD, INSTALL, OR USE THE PROGRAM, AND YOU MUST DELETE OR RETURN THE UNUSED PROGRAM TO THE VENDOR FROM WHICH YOU ACQUIRED IT WITHIN THIRTY (30) DAYS. \
 \
1.	DEFINITIONS. \
 \
1.1	\&quot;Documentation\&quot; means that documentation that is generally provided to You by VMware with the Program, as revised by VMware from time to time, and which may include end user manuals, operation instructions, installation guides, release notes, and on-line help files regarding the use of the Program. \
 \
1.2	\&quot;GPL v2\&quot; means the GNU General Public License version 2 the terms of which are available at http://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html. \
 \
1.3	\&quot;Intellectual Property Rights\&quot; means all worldwide intellectual property rights, including without limitation, copyrights, trademarks, service marks, trade secrets, know how, inventions, patents, patent applications, moral rights and all other proprietary rights, whether registered or unregistered. \
 \
1.4	\&quot;Open Source Software\&quot; or \&quot;OSS\&quot; means software components embedded in the Program and provided under separate license terms, which can be found either in the open_source_licenses.txt file (or similar file) provided with the Program or at the Photon OS source repository at https://github.com/vmware/photon. \
 \
1.5	\&quot;Program\&quot; means the computer programs included in the object code version of Photon OS. \
 \
1.6	\&quot;VMware\&quot; means VMware, Inc., a Delaware corporation, if You are purchasing services for use in the United States and VMware International Limited, a company organized and existing under the laws of Ireland, for all other purchases. \
2.		LICENSE GRANT. \
 \
2.1	General License Grant.  VMware grants to You a license to use the Program pursuant to the terms of the GPL v2. \
 \
2.2	Open Source Software.  Notwithstanding anything herein to the contrary, Open Source Software is licensed to You under such OSS\&apos;s own applicable license terms, which can be found in the open_source_licenses.txt file, or the corresponding source files for the Program available at https://github.com/vmware/photon. To the extent the license for any Open Source Software requires VMware to make available to You the corresponding source code and/or modifications (the \&quot;Source Files\&quot;), You may obtain a copy of the applicable Source Files from the Photon OS source repository at  https://github.com/vmware/photon or by sending a written request, with Your name and address to: VMware, Inc., 3401 Hillview Avenue, Palo Alto, CA 94304, United States of America. All requests should clearly specify:  Open Source Files Request, Attention: General Counsel.  This offer to obtain a copy of the Source Files is valid for three years from the date You acquired this Program. \
 \
2.3	Copying of Documentation Permitted. You may copy the Documentation as necessary to install, run and use the Program, but otherwise for archival purposes only. \
 \
2.4	Restrictions.  You are not authorized to redistribute modified versions of the Program with VMware trademarks and logos. \
 \
2.5	Intellectual Property in Trademarks and Documentation.  Notwithstanding the terms applicable to the Program, VMware and its licensors retain all ownership in VMware trademarks and the Documentation, including all modifications, enhancements and derivative works thereof, and all Intellectual Property Rights therein. Your rights to use the Documentation and VMware trademarks are limited to those expressly granted in this EULA, and no other rights are implied. \
 \
3.	SUPPORT AND SUBSCRIPTION SERVICES.  VMware does not provide any support or subscription services for the Program under this EULA. \
 \
4.	DATA PRIVACY. You agree that VMware may process technical and related information about Your use of the Program which may include internet protocol address, hardware identification, operating system, application software, peripheral hardware, and non-personally identifiable Program usage statistics to facilitate the provisioning of online services and may transfer such information to other companies in the VMware worldwide group of companies from time to time. To the extent that this information constitutes personal data, VMware shall be the controller of such personal data. To the extent that it acts as a controller, each party shall comply at all times with its obligations under applicable data protection legislation. \
 \
5.	WARRANTY DISCLAIMER AND LIMITATION OF LIABILITY \
 \
5.1	Limitation of Liability. IN ADDITION TO ANY AND ALL LIMITATION OF LIABILITY IN THE GPL V2, IN RESPECT TO THE DOCUMENTATION AND OTHERWISE, TO THE MAXIMUM EXTENT MANDATED BY LAW, IN NO EVENT WILL VMWARE AND ITS LICENSORS BE LIABLE FOR ANY LOST PROFITS OR BUSINESS OPPORTUNITIES, LOSS OF USE, LOSS OF REVENUE, LOSS OF GOODWILL, BUSINESS INTERRUPTION, LOSS OF DATA, OR ANY INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES UNDER ANY THEORY OF LIABILITY, WHETHER BASED IN CONTRACT, TORT, NEGLIGENCE, PRODUCT LIABILITY, OR OTHERWISE.  BECAUSE SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE PRECEDING LIMITATION MAY NOT APPLY TO YOU.  VMWARE\&apos;S AND ITS LICENSORS\&apos; LIABILITY UNDER THIS EULA WILL NOT, IN ANY EVENT, REGARDLESS OF WHETHER THE CLAIM IS BASED IN CONTRACT, TORT, STRICT LIABILITY, OR OTHERWISE, EXCEED USD$100. THE FOREGOING LIMITATIONS SHALL APPLY REGARDLESS OF WHETHER VMWARE OR ITS LICENSORS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND REGARDLESS OF WHETHER ANY REMEDY FAILS OF ITS ESSENTIAL PURPOSE. \
 \
5.2	Further Limitations.  VMware\&apos;s licensors shall have no liability of any kind under this EULA and VMware\&apos;s liability with respect to any third party software embedded in the Program shall be subject to Section 5.1 (Limitation of Liability).  You may not bring a claim under this EULA more than eighteen (18) months after the cause of action arises. \
 \
5.3	Documentation Warranty Disclaimer: TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, VMWARE AND ITS LICENSORS MAKE NO EXPRESS WARRANTIES UNDER THIS EULA IN RESPECT TO THE DOCUMENTATION OR OTHERWISE, AND DISCLAIM ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT, AND ANY WARRANTY ARISING BY STATUTE, OPERATION OF LAW, COURSE OF DEALING OR PERFORMANCE, OR USAGE OF TRADE. VMWARE AND ITS LICENSORS DO NOT WARRANT THAT THE DOCUMENTATION WILL BE FREE FROM DEFECTS OR THAT IT WILL MEET YOUR REQUIREMENTS. \
 \
6.	COMPLIANCE WITH LAWS; EXPORT CONTROL; GOVERNMENT REGULATIONS.  Each party shall comply with all laws applicable to the actions contemplated by this EULA. You acknowledge that the Program is of United States origin, is provided subject to the U.S. Export Administration Regulations, may be subject to the export control laws of the applicable territory, and that diversion contrary to applicable export control laws is prohibited. You represent that (1) you are not, and are not acting on behalf of, (a) any person who is a citizen, national, or resident of, or who is controlled by the government of any country to which the United States has prohibited export transactions; or (b) any person or entity listed on the U.S. Treasury Department list of Specially Designated Nationals and Blocked Persons, or the U.S. Commerce Department Denied Persons List or Entity List; and (2) you will not permit the Program to be used for, any purposes prohibited by law, including, any prohibited development, design, manufacture or production of missiles or nuclear, chemical or biological weapons. The Program and Documentation are deemed to be \&quot;commercial computer software\&quot; and \&quot;commercial computer software documentation\&quot;, respectively, pursuant to DFARS Section 227.7202 and FAR Section 12.212(b), as applicable.  Any use, modification, reproduction, release, performing, displaying or disclosing of the Program and Documentation by or for the U.S. Government shall be governed solely by the terms and conditions of this EULA. \
 \
7.	GOVERNING LAW.  This EULA is governed by the laws of the State of California, United States of America (excluding its conflict of law rules), and the federal laws of the United States. To the extent permitted by law, the state and federal courts located in Santa Clara County, California will be the exclusive jurisdiction for disputes arising out of or in connection with this EULA. The U.N. Convention on Contracts for the International Sale of Goods does not apply. \
 \
Photon OS 1.0 GA EULA_2016May19 \
\
      </License> \
    </EulaSection> \
    <VirtualHardwareSection@' ${outputVM}.ovf

if [ ! -z "$customscript" ]; then
    eval $customscript $inputVM $outputVM
fi

newOvfSha=$(sha1sum ${outputVM}.ovf | awk '{ print $1 }')
sed -i.bak "s/$oldOvfSha/$newOvfSha/" ${outputVM}.mf

tar cvf ${outputVM}.ova ${outputVM}.ovf ${outputVM}*.vmdk ${outputVM}.mf
rm *.ovf
rm *.mf
rm *.vmdk
rm *.bak
