#!/usr/bin/env python
# Copyright 2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, without
# warranties or conditions of any kind, EITHER EXPRESS OR IMPLIED.  See the
# License for then specific language governing permissions and limitations
# under the License.

import sys
from string import Template

if len(sys.argv) < 4 or len(sys.argv) % 2 != 0:
    print "Usage: %s file key1 value1 key2 value2" % sys.argv[0]
    sys.exit(1)

with open(sys.argv[1], "r") as f:
    contents = f.read()
    template = Template(contents)

    it = iter(sys.argv[2:])
    mapping = dict(zip(it, it))

    print(template.substitute(mapping))
