#!/bin/bash -ex
# Copyright 2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, without
# warranties or conditions of any kind, EITHER EXPRESS OR IMPLIED.  See the
# License for then specific language governing permissions and limitations
# under the License.

export ESX_PWD=$1

# Define any custom config process
if [ -n "$CUSTOM_TEST_CONFIG" ]; then
    echo Using custom settings in $CUSTOM_TEST_CONFIG
    source $CUSTOM_TEST_CONFIG
else
    echo No CUSTOM_TEST_CONFIG to override default test behavior
fi

env

checklist="\
  DATASTORE_DIR\
  ESX_IP\
  ESX_DATASTORE\
  IMAGES_DIR\
  ISO_DATASTORE_DIR\
  ISO_DIR"

for var in $checklist; do
  if [ -z "$(printenv $var)" ]; then
      echo Cannot run test. $var is not defined.
      echo This list of properties must be defined. $checklist
      exit 1
  fi
done

echo "Using ESX server $ESX_IP"

cd $WORKSPACE
git submodule update --init

cd $WORKSPACE/python
make clean
make develop


make vib DEBUG=1

sshpass -p "$ESX_PWD" ssh root@$ESX_IP 'rm /tmp/*.vib' || true
sshpass -p "$ESX_PWD" scp ./dist/photon-controller-agent-*.vib root@$ESX_IP:/tmp
sshpass -p "$ESX_PWD" ssh root@$ESX_IP 'wget http://build-squid.eng.vmware.com/build/mts/release/sb-7471046/publish/uw32/packages/vmware-envoy-6.0.3-7471046.vib -P /tmp/'
sshpass -p "$ESX_PWD" ssh root@$ESX_IP 'esxcli software vib remove -f -n photon-controller-agent' || true
sshpass -p "$ESX_PWD" ssh root@$ESX_IP 'esxcli software vib install -f -v /tmp/photon-controller-agent-*.vib'
sshpass -p "$ESX_PWD" ssh root@$ESX_IP 'esxcli software vib remove -f -n envoy' || true
sshpass -p "$ESX_PWD" ssh root@$ESX_IP 'esxcli software vib install -f -v /tmp/vmware-envoy-*.vib'

sshpass -p "$ESX_PWD" ssh root@$ESX_IP 'esxcfg-vswitch -a test' || true
sshpass -p "$ESX_PWD" ssh root@$ESX_IP 'esxcfg-vswitch -A "VM Network" test' || true
sshpass -p "$ESX_PWD" ssh root@$ESX_IP 'vim-cmd hostsvc/net/refresh' || true
sshpass -p "$ESX_PWD" ssh root@$ESX_IP -t -t '/etc/init.d/photon-controller-agent restart'

IMAGE_SUB_DIR=image_ttylinux

# Copy the ttylinux image and metadata to datastore
sshpass -p "$ESX_PWD" ssh root@$ESX_IP "mkdir -p $DATASTORE_DIR/$IMAGE_SUB_DIR" || true
sshpass -p "$ESX_PWD" scp $IMAGES_DIR/* root@$ESX_IP:$DATASTORE_DIR/$IMAGE_SUB_DIR/

# Copy the test iso to datastore
sshpass -p "$ESX_PWD" scp $ISO_DIR/* root@$ESX_IP:$ISO_DATASTORE_DIR/

ESX_PWD_ESCAPE=$(echo $ESX_PWD | sed 's/\$/$$/g')
# Save return code from the test run and copy the agent log.
if [ -n "$SANITY" ]; then
  make -s test -C src/agent VERBOSE_REPORT=1 XUNIT=1 INTEGRATION=1 \
    REMOTE_SERVER=$ESX_IP DATASTORES=$ESX_DATASTORE \
    REMOTE_ISO="[$ESX_DATASTORE] $ISO_NAME" \
    DISABLE_HYPERVISOR_LOGGING=1 SANITY=1 \
    || make_return_code=$?
else
  make -s test VERBOSE_REPORT=1 XUNIT=1 INTEGRATION=1 \
    ESX_PWD=$ESX_PWD_ESCAPE REMOTE_SERVER=$ESX_IP DATASTORES=$ESX_DATASTORE \
    REMOTE_ISO="[$ESX_DATASTORE] $ISO_NAME" \
    DISABLE_HYPERVISOR_LOGGING=1 \
    || make_return_code=$?
fi

sshpass -p "$ESX_PWD" scp root@$ESX_IP:/var/log/photon-controller-agent.log . || true

exit $make_return_code
