#!/bin/bash
# Copyright 2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, without
# warranties or conditions of any kind, EITHER EXPRESS OR IMPLIED.  See the
# License for then specific language governing permissions and limitations
# under the License.

# Validate args
if [ -z "$1" ]; then
    echo "Usage: $0 PORT"
    exit 1
fi

if [ ! -x $ZOOKEEPER_PATH/bin/zkServer.sh ]; then
  echo "ZOOKEEPER_PATH must be set to an extracted distribution"
  exit 1
fi

PORT=$1

# Create zookeeper instance directory (logs and conf)
TMPDIR=`mktemp -d -t zookeeper.XXXXX`

# Make sure we're in the right location
cd "$(dirname "$0")"

# Fill in zookeeper configuration template
(cd zookeeper; tar cf - . | (cd $TMPDIR && tar xf -))
./fill_template zookeeper/zoo.cfg DIR $TMPDIR/data PORT $PORT > $TMPDIR/zoo.cfg

# Start zookeeper suppressing all output
ZOO_LOG_DIR=$TMPDIR $ZOOKEEPER_PATH/bin/zkServer.sh start $TMPDIR/zoo.cfg &> $TMPDIR/std.log

if [ $? -ne 0 ]; then
    echo "error starting zookeeper"
    cat $TMPDIR/std.log
    rm -rf $TMPDIR
    exit 1
fi

# Output instance directory that can be used by the ./stop_zk script
echo $TMPDIR
