#!/bin/bash -e
# Copyright 2015 VMware, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not
# use this file except in compliance with the License.  You may obtain a copy
# of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, without
# warranties or conditions of any kind, EITHER EXPRESS OR IMPLIED.  See the
# License for then specific language governing permissions and limitations
# under the License.

# Validate args
if [ -z "$1" ]; then
    echo "Usage: $0 DIR"
    exit 1
fi

DIR=$1
if [ ! -f $DIR/zoo.cfg ]; then
  echo "DIR must point to a directory with a zoo.cfg"
  exit 1
fi

if [ ! -x $ZOOKEEPER_PATH/bin/zkServer.sh ]; then
  echo "ZOOKEEPER_PATH must be set to an extracted distribution"
  exit 1
fi

# Stop zookeeper
ZOO_LOG_DIR=$DIR $ZOOKEEPER_PATH/bin/zkServer.sh stop $DIR/zoo.cfg

# Delete zookeeper instance dir
rm -rf $DIR
